# custom.***と言う名前で認識してくれる。
[custom.cdk]
# プロンプトに表示される内容。実行結果が$output変数に格納される。
command = "echo $CDK_VERSION"
# cdkのバージョンを表示する条件。
# 実行するディレクトリに`cdk.json`がある場合
when = """ test -e cdk.json """
# シンボル
symbol = "cdk: "
# 表示のフォーマット
format = "[$symbol$output]($style)"

# 改行自体の設定
[line_break]
disabled = true # 非表示に設定

# 時間の設定
[time]
disabled = true # 非表示に設定すると、必ず一行になる

# gitのブランチの表示
[git_branch]
symbol = "🌱 " #アイコン絵文字を変更

# gitのstatusの表示
[git_status]
modified = "+" #ファイルの変更がある場合の表示を変更
